name: fluttermasters
workflows:
  flutter_masters_prod: 
    environment:
     groups:
       - "Firebase"
       
     flutter: stable
     java: 11
     ios_signing: 
       certificates:
         - FlutterMasterDevelopCertificate
       provisioning_profiles:
         - FlutterMasterProvisionProfile

    triggering:
     events:
        - "push"
     branch_patterns:
       - include: true
         source: true
         pattern: github-actions

    scripts:
      - name: INIT KEYCHAIN
        script: keychain initialize
      - name: ADD CERTIFICATES
        script: keychain add-certificates
      - name: SET PROVISIONING PROFILES
        script: xcode-project use-profiles
      - name: GENERATE APK
        script: flutter build apk --release
      - name: GENERATE IPA
        script: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist

    artifacts:
      -  build/ios/ipa/Apps/clean_architecture.ipa
      -  build/app/outputs/flutter-apk/app-release.apk
      
    publishing:
     firebase:
      firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
      android:
       artifact_type: apk
       app_id: 1:927233104549:android:56747debe9c0c55fdc8b4c
      
      
      ios:
       app_id: 1:927233104549:ios:6e7663cbe53d4358dc8b4c
       groups:
         - "testers"